### PR TITLE
[Feature] Add support for step-level monitoring (e.g. RankMe, etc.)

### PR DESCRIPTION
**Pull request by sami-bg**
Adds support for metrics (just RankMe, for now) that are computed at the end of each step (e.g. fit_step, eval_step), whereas torchmetrics.Metrics only supports end-of-epoch metrics.

There are a handful of design choices that could use more thought:
1. Different metrics (e.g. GradNorm, RankMe, etc.) require different inputs. For now, the Monitor base class assumes we are getting the model output (e.g. encoding) as input, which is sufficient for RankMe. In the future, we might want to pass the entire BaseModel instance.

2. In the straightforward case of RankMe, the latest model output is stored in a property and passing it as `x` in whenever `monitor.compute(x)` is called.

3. The default window size for RankMe (8) is adjusted based on world size. For 2 devices, each device holds 4 batches, and the rank 0 device handles computing the RankMe. This overhead would mean that the rank 0 device (and consequently, all other devices) need to accommodate an extra 8 batches worth of memory to compute the rankme score.

I tested this with the `simclr_cifar10_full.yaml` config and it seems to work, but I was unable to test the DDP case yet. Let me know what you think!

### CODE REVIEW

**Comment by huguesva** [comment]
Hey @sami-bg, I will review it shortly but is seems very appropriate, thanks a lot!

**Comment by huguesva** [comment]
Hello @sami-bg ! are you sure there is no implementation of rankme out there that works with float16?

**Comment by sami-bg** [comment]
Howdy! I haven't looked in too much detail - but from what I've read ([this ](https://github.com/NVIDIA/apex/issues/887) github issue), `torch.linalg.svd` does not support half precision types, and I think the limitation might be all the way down at the cuSolver not supporting half precision.

**Comment by RandallBalestriero** [comment]
@sami-bg thank you for that contribution! Adding RankMe is definitely needed. In case we have some time after we could look into adding LiDAR (https://arxiv.org/abs/2312.04000) as well although it may be more involved as it requires to probe multiple views. Perhaps we just want to create a utility function to compute the LiDAR value and then let users do the rest @huguesva

**Comment by huguesva** [comment]
Thanks a lot @sami-bg and welcome to the contributors! Please feel free to contribute any time! Merry christmas :)

**Comment by sami-bg** [comment]
Thank you both! Merry Christmas and I'm looking forward to contributing & seeing how this library evolves :)

**Pull request merged**
